### PR TITLE
Use the webpack 2 chunk api

### LINKED ISSUE #12: Plugin errors in webpack 2
Because there is a change in Chunk api, this plugin errors with webpack 2. There error is:

``` bash
ERROR in chunk vendor [entry]
app-9148709000831c41a110.js
Chunk.entry was removed. Use hasRuntime()
```

I have a simple fix in a fork. I know webpack 2 is beta but would you accept a PR?

### PR DESCRIPTION
**Pull request by kentcdodds**
Call chunk.hasRuntime() instead of checking chunk.entry.

From @brandondoran's fork

Closes #12

### CODE REVIEW

**Comment by kentcdodds** [comment]
I can verify that this solves the problem for my case 👍

**Comment by kentcdodds** [comment]
FYI, I no longer will be using this. I'll be using [inline-manifest-webpack-plugin](https://github.com/szrenwei/inline-manifest-webpack-plugin) instead. Though others probably still care that this gets merged.

**Comment by hung-phan** [comment]
Any plan to merge this PR?

**Comment by brandondoran** [comment]
I created a repo to demo using CommunChunksPlugin to create a separate manifest.js along with NamedModulePlugin, HtmlWebpackPlugin and inline-manifest-webpack-plugin to accomplish long term caching: https://github.com/brandondoran/react-webpack-tutorial

**Comment by cellis** [comment]
Please merge this

**Comment by brandondoran** [comment]
Hi @diurnalist. First, thanks for creating this plugin. It's helped lots of people get long term caching working with webpack! As more and more people move to webpack 2 they will find their build breaks since chunk-manifest-webpack-plugin doesn't work in webpack 2. It sounds like webpack 2 is pretty close to coming out of beta. Would you consider merging this to alleviate that breakage?

**Comment by diurnalist** [comment]
@brandondoran thanks for the ping. I don't really get alerted to activity on these little things I've written except for explicit mentions like that. I plan on moving this under the SoundCloud org to hopefully add a bit more accountability to maintenance.

**Comment by diurnalist** [comment]
Published as 1.0.0, sorry for the wait

**Comment by brandondoran** [comment]
Awesome! Thanks @diurnalist. Sounds good on moving to under the org. BTW

**Pull request merged**
